### Config file for host transcriptomics pipeline
### RE 10/2022

# n.b., host_genome is the directory where the genome is stored, not the file itself.
host_genome: /projects/mjolnir1/people/ncl550/1_projects/2022_ChickenTrascriptomics/Host_transcriptomics_pipeline/1_References
annotation: /projects/mjolnir1/people/ncl550/1_projects/2022_ChickenTrascriptomics/Host_transcriptomics_pipeline/1_References/GCF_000002315.6_GRCg6a_genomic.gtf